apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: beeper-backend
  namespace: beeper
  labels:
    app: beeper-backend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/yosseer/DevOps-Incident-Board.git
      ref: main
    contextDir: beeper-backend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: beeper-backend:latest
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: beeper-backend
  namespace: beeper
  labels:
    app: beeper-backend
spec:
  lookupPolicy:
    local: false
